authentication/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm, ChangePasswordForm, PwdResetForm, PwdResetConfirmForm
app_name = 'auth'

urlpatterns = [
    path('registration/',views.registration_view.as_view(),name='reg'),
    path('',auth_views.LoginView.as_view(template_name='authentication/login.html',authentication_form=LoginForm), name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='auth:login'),name='logout'),
    path('passwordchange/',auth_views.PasswordChangeView.as_view(template_name='authentication/change_pwd.html',form_class = ChangePasswordForm, success_url = '/pwdchdone/'),name='pwdchange'),
    path('pwdchdone/',auth_views.PasswordChangeView.as_view(template_name='authentication/pwdchdone.html'),name='pwdchdone'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='authentication/pwd_reset.html',email_template_name = 'authentication/password_reset_email.html', success_url = reverse_lazy('auth:password_reset_done'), form_class = PwdResetForm), name = 'password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='authentication/pwd_reset_done.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='authentication/pwd_reset_confirm.html',success_url = reverse_lazy('auth:password_reset_complete'), form_class=PwdResetConfirmForm), name = 'password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='authentication/pwd_reset_complete.html'), name = 'password_reset_complete'),
    
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base_auth_final/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls',namespace='auth')),
    path('createTeams/',include('createTeams.urls',namespace='createTeams')),
    path('video_call/',include('video_call.urls',namespace='video_call')),
    path('accounts/', include('allauth.urls')),
]

video_call/urls.py
from django.urls import path
from .views import *
app_name = 'video_call'
urlpatterns = [
    path('<int:team_id>/<uuid:room_id>',main_view,name="main_view"),
    path('invite_people/',invite_people,name="invite_people")
]

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import password_validation

class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(label = 'Password',widget = forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label = 'Confirm Password',widget = forms.PasswordInput(attrs={'class':'form-control'}))
    email = forms.CharField(required=True,widget = forms.EmailInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        labels = {'email':'Email'}
        widgets = {'username':forms.TextInput(attrs={'class':'form-control'})}

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True,'class':'form-control'}))
    # email = forms.CharField(required=True,widget = forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(label = _("Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'current-password','class':'form-control'}))

class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label = _("Old Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'current-password','class':'form-control','autofocus':True,'class':'form-control'}))
    new_password1 = forms.CharField(label = _("New Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'new-password','class':'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label = _("Confirm Password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'new-password','class':'form-control'}))

class PwdResetForm(PasswordResetForm):
    email = forms.EmailField(label = _("Email"), max_length = 254, widget = forms.EmailInput(attrs={'autocomplete':'email','class':'form-control'}))

class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(label=_("New password"),strip=False, widget=forms.PasswordInput(attrs = {'autocomplete':'new-password','class':'form-control'}),help_text=password_validation.password_validators_help_text_html)
    new_password2 = forms.CharField(label=_("New password confirmation"),widget=forms.PasswordInput(attrs = {'autocomplete':'new-password','class':'form-control'}))

authentication/views.py
from django.shortcuts import render
from django.views import View
from .forms import RegistrationForm
from django.contrib import messages
from django.contrib.auth.models import User

class registration_view(View):
    def get(self,request):
        form = RegistrationForm()
        return render(request, 'authentication/reg.html',{'form':form})
    def post(self,request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            messages.success(request,'Congratulations!! Registered Successfully')
            form.save()
        return render(request, 'authentication/reg.html',{'form':form})

authentication/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

    <head>
		<meta charset="utf-8">
		{% block title %}{% endblock title %}
		<meta name="description" content="#">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="{% static 'dist/css/lib/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'dist/css/swipe.min.css' %}" type="text/css" rel="stylesheet">
		{% block mycss %}{% endblock mycss %}
    </head>
    <body>
		{% block main-content %}{% endblock main-content %}
		
		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="{% static 'dist/js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script>window.jQuery || document.write('<script src="{% static "dist/js/vendor/jquery-slim.min.js" %}"><\/script>')</script>
		<script src="{% static 'dist/js/vendor/popper.min.js' %}"></script>
		<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
		<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    </body>
</html>

authentication/templates/authentication/change_pwd.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}<title>Sign In</title>{% endblock title %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content">
                        <h1>Change Password</h1>
                        <form action="" method="post" novalidate class="p-5" style="box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(80, 88, 94);">
                            {% csrf_token %}
                            {% for fm in form %} 
                            <div class="mb-2">
                            {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small>
                            </div>
                            {% endfor %}<br>
                            <input type = "submit" value="Submit" class="btn button" style="size: 15">
                            <br><br>
                            {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                            <p class="alert alert-danger my-3">{{error}}</p>
                            {% endfor %}
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>            
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>Don't worry if you forgot your password. Click here!!</p>
                    <a href="{% url 'auth:password_reset' %}" class="btn button">Forgot Password?</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}

authentication/templates/authentication/login.html
{% extends 'authentication/base.html' %}
{% load socialaccount %}
{% load static %}
{% block title %}<title>Sign In</title>{% endblock title %}
{% block mycss %}
<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content= "556039925162-c2a27uadh1off8jf0j16mgolk0783cve.apps.googleusercontent.com">

{% endblock mycss %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content">
                        <h1>Sign In to Teams</h1>
                        <form action="" method="post" novalidate class="p-5" style="box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(80, 88, 94);">
                            {% if messages %}
                            {% for message in messages %}
                            <p {% if message.tags %} class = "alert alert -{{message.tags}} mb-5" style = "background-color: #ad979d; color:black"{% endif %}>{{message}}</p>
                            {% endfor %}
                            {% endif %}
                            {% csrf_token %}
                            {% for fm in form %} 
                            <div class="mb-2">
                            {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small>
                            </div>
                            {% endfor %}
                            <small><a href="{% url 'auth:password_reset' %}">Forgot Password ?</a></small><br><br>
                            <input type = "submit" value="Submit" class="btn button" style="size: 15">
                            <br><br>
                            <div class="text-center text-primary fw-bold"><small>New User ? <a href="{% url 'auth:reg' %}"
                                class="text-danger">Create an Account</a> </small></div>
                            {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                            <p class="alert alert-danger my-3">{{error}}</p>
                            {% endfor %}
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>            
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>To keep connected please register with your info.</p>
                    <a href="{% url 'auth:reg' %}" class="btn button">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}

authentication/templates/authentication/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link
below:
{{ protocol }}://teamss-clone.herokuapp.com{% url 'auth:password_reset_confirm' uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

authentication/templates/authentication/pwd_reset.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}<title>Password Reset Confirm</title>{% endblock title %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content">
                        <h1>Reset Password</h1>
                        <form action="" method="post" novalidate class="p-5" style="box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(80, 88, 94);">
                            {% csrf_token %}
                            {% for fm in form %} 
                            <div class="mb-2">
                            {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small>
                            </div>
                            {% endfor %}
                            <input type = "submit" value="Submit" class="btn button" style="size: 15">
                            <br><br>
                            <div class="text-center text-primary fw-bold"><small>New User ? <a href="{% url 'auth:reg' %}"
                                class="text-danger">Create an Account</a> </small></div>
                            {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                            <p class="alert alert-danger my-3">{{error}}</p>
                            {% endfor %}
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>            
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>To keep connected please register with your info.</p>
                    <a href="{% url 'auth:reg' %}" class="btn button">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}

authentication/templates/authentication/pwd_reset_complete.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}<title>Password Reset Complete</title>{% endblock title %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content" >
                        <h3 >Password Reset Completed Successfully !!</h3><br>
                        <div class="wishImg">
                            <img src="{% static 'images/pwd_comp.gif' %}" width="330" height="270" style="align-items: center; padding-left: 10%;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>To keep connected please login with your info.</p>
                    <a href="{% url 'auth:login' %}" class="btn button">Sign In</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}

authentication/templates/authentication/pwd_reset_confirm.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}<title>Password Reset Confirm</title>{% endblock title %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content">
                        <h1>Reset Password</h1>
                        <form action="" method="post" novalidate class="p-5" style="box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(80, 88, 94);">
                            {% csrf_token %}
                            {% for fm in form %} 
                            <div class="mb-2">
                            {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small>
                            </div>
                            {% endfor %}
                            <input type = "submit" value="Submit" class="btn button" style="size: 15">
                            <br><br>
                            <div class="text-center text-primary fw-bold"><small>New User ? <a href="{% url 'auth:reg' %}"
                                class="text-danger">Create an Account</a> </small></div>
                            {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                            <p class="alert alert-danger my-3">{{error}}</p>
                            {% endfor %}
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>            
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>To keep connected please register with your info.</p>
                    <a href="{% url 'auth:reg' %}" class="btn button">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}

authentication/templates/authentication/pwd_reset_done.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}<title>Reset Password </title>{% endblock title %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content" >
                        <h3 >Mail sent to email box. Check your email !!</h3><br>
                        <div>
                            <img src="{% static 'images/pwd_reset_email_sent.png' %}" width="330" height="270" style="align-items: center; padding-left: 10%;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>To keep connected please register with your info.</p>
                    <a href="{% url 'auth:reg' %}" class="btn button">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}

authentication/templates/authentication/pwdchdone.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}<title>Password Change Complete</title>{% endblock title %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content" >
                        <h3>Password Changed Successfully !!</h3><br>
                        <div class="wishImg">
                            <img src="{% static 'images/pwd_comp.gif' %}" width="330" height="270" style="align-items: center; padding-left: 10%;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>To keep connected please login with your info.</p>
                    <a href="{% url 'auth:login' %}" class="btn button">Sign In</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}

authentication/templates/authentication/reg.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}<title>Sign Up</title>{% endblock title %}
{% block main-content %}
<div class="layout">
    <div class="main order-md-2">
        <div class="start">
            <div class="container">
                <div class="col-md-12">
                    <div class="content">
                        <h1>Create Account</h1>
                        <form action="" method="post" novalidate class="p-5" style="box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(80, 88, 94);">
                            {% if messages %}
                            {% for message in messages %}
                            <p {% if message.tags %} class = "alert alert -{{message.tags}} mb-5" style = "background-color: #ad979d; color:black"{% endif %}>{{message}}</p>
                            {% endfor %}
                            {% endif %}
                            {% csrf_token %}
                            {% for fm in form %} 
                            <div class="mb-2">
                            {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small>
                            </div>
                            {% endfor %}
                            <input type = "submit" value="Submit" class="btn button" style="size: 15">
                            <br><br>
                            <div class="text-center text-primary fw-bold"><small>Existing User ? <a href="{% url 'auth:login' %}"
                                class="text-danger">Login Now</a> </small></div>
                            {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                            <p class="alert alert-danger my-3">{{error}}</p>
                            {% endfor %}
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>            
    <div class="aside order-md-1">
        <div class="container">
            <div class="col-md-12">
                <div class="preference">
                    <h2>Welcome Back!</h2>
                    <p>To keep connected please login with your info.</p>
                    <a href="{% url 'auth:login' %}" class="btn button">Sign In</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}