authentication/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm, ChangePasswordForm, PwdResetForm, PwdResetConfirmForm
app_name = 'auth'

urlpatterns = [
    path('registration/',views.registration_view.as_view(),name='reg'),
    path('',auth_views.LoginView.as_view(template_name='authentication/login.html',authentication_form=LoginForm), name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='auth:login'),name='logout'),
    path('passwordchange/',auth_views.PasswordChangeView.as_view(template_name='authentication/change_pwd.html',form_class = ChangePasswordForm, success_url = '/pwdchdone/'),name='pwdchange'),
    path('pwdchdone/',auth_views.PasswordChangeView.as_view(template_name='authentication/pwdchdone.html'),name='pwdchdone'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='authentication/pwd_reset.html',email_template_name = 'authentication/password_reset_email.html', success_url = reverse_lazy('auth:password_reset_done'), form_class = PwdResetForm), name = 'password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='authentication/pwd_reset_done.html'), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='authentication/pwd_reset_confirm.html',success_url = reverse_lazy('auth:password_reset_complete'), form_class=PwdResetConfirmForm), name = 'password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='authentication/pwd_reset_complete.html'), name = 'password_reset_complete'),
    
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base_auth_final/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls',namespace='auth')),
    path('createTeams/',include('createTeams.urls',namespace='createTeams')),
    path('video_call/',include('video_call.urls',namespace='video_call')),
    path('accounts/', include('allauth.urls')),
]

createTeams/urls.py
from django.urls import path
from . import views
app_name='createTeams'

urlpatterns=[
    path('create_new_team/',views.create_new_team, name="new_team"),
    path('create_team/<int:par_id>', views.create_team, name="create_team"),
    path('display_teams/',views.display_teams, name="display_teams"),
    path('edit_team/<int:org_id>', views.edit_team, name="edit_team"),
    path('view_team/<int:team_id>', views.view_team,name = 'view_team'),
    path('change_role/<int:org_id>', views.change_role,name = 'change_role'),
    path('dismiss_admin/<int:org_id>', views.dismiss_admin,name = 'dismiss_admin'),
    path('leave_team/<int:org_id>', views.leave_team,name = 'leave_team'),
    path('delete_team/<int:org_id>', views.delete_team,name = 'delete_team'),
    path('add_members/<int:org_id>', views.add_members,name = 'add_members'),
    path('send_invite/<int:org_id>', views.send_invite,name = 'send_invite'),
]

video_call/urls.py
from django.urls import path
from .views import *
app_name = 'video_call'
urlpatterns = [
    path('<int:team_id>/<uuid:room_id>',main_view,name="main_view"),
    path('invite_people/',invite_people,name="invite_people")
]

createTeams/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from .models import Organization,Membershiplevel, Team_Messages
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail
import uuid
import json

'''
View being called to display all the teams, user is a part of.
'''
def display_teams(request):
    if not request.user.is_authenticated:
        return redirect('/')
    memberships = Membershiplevel.objects.filter(user__username = request.user.username)
    teams = []
    for membership in memberships:
        org_id = membership.organization.id
        org = Organization.objects.get(pk=org_id)
        if org.parent_org_id is None:
            teams.append(org)
    return render(request,'createTeams/display_teams.html',{'teams':teams,'username':request.user.username})


'''
Function being called by other views to retrieve all the channels( child organizations) for the team.
As sub-channels may also exist for other channels,
so we are calling recursive function to retrieve all the channels
''' 
def retrieve_child_org(parent,child):
    count = Organization.objects.filter(parent_org = parent).count()
    if count!=0:
        child_org = Organization.objects.filter(parent_org = parent)
        for i in child_org:
            retrieve_child_org(i.id,child)
            child.append(i.id)


'''
View being called for creating the channel(sub-organisation of Team).
It checks if the channel with the same name already exists,
if exists, then it gives the warning "Channel cannot be created"
else it successfully creates the new channel.
'''
def create_team(request,par_id) :
    if request.user.is_authenticated:
        warning = ''
        if request.method == 'POST':
            channel_name = request.POST['team_name']
            members = request.POST.getlist('checks')
            print(members)
            user=request.user
            description = request.POST['description']
            if Organization.objects.filter(name = channel_name,parent_org__id = par_id).exists():
                warning = "Channel with this name already exists"
            else: 
                channel = Organization.objects.create(name = channel_name,parent_org_id = par_id,description=description)
                members = User.objects.filter(pk__in = members)
                Membershiplevel.create_team(members,channel,par_id,request.user.id)
                warning = "Channel created"
                return redirect(reverse("createTeams:view_team",kwargs={'team_id':channel.id}))
        memberships = Membershiplevel.objects.filter(organization__id = par_id)
        return render(request,'createTeams/create_channel.html',{'memberships':memberships,'warning':warning,'user':request.user},)
    else:
        return redirect('/')


'''
View being called for creating the new team.
It checks if the team with the same name already exists, it gives warning "Team cannot be created"
else it successfully creates the new team.
'''
def create_new_team(request):
    if request.user.is_authenticated:
        warning = ''
        if request.method == 'POST':
            team_name = request.POST['team_name']
            members = request.POST.getlist('checks')
            user=request.user
            description = request.POST['description']
            print(members)
            if Organization.objects.filter(name = team_name,parent_org__id = None).exists():
                warning = "Team with this name already exists"
            else:
                team = Organization.objects.create(name = team_name,parent_org_id = None,description=description)
                members = User.objects.filter(pk__in = members)
                Membershiplevel.create_team(members,team,None,request.user.id)
                warning = "team created"
                return redirect(reverse("createTeams:view_team",kwargs={'team_id':team.id}))
        memberships = User.objects.all()
        print(memberships)
        return render(request,'createTeams/create_team.html',{'memberships':memberships,'warning':warning,'user':request.user},)
    else:
        return redirect('/')


'''
View used to change the status of members from participant to admin(owner) 
'''
def change_role(request,org_id):
    if request.user.is_authenticated:
        warning = ''
        role = Membershiplevel.objects.get(organization__id = org_id , user_id = request.user.id).role
        if request.method == 'POST':
            members = request.POST.getlist('checks')
            members = User.objects.filter(pk__in = members)
            Membershiplevel.change_role(members,org_id)
            warning = "Role changed to admin successfully!!"
        memberships = Membershiplevel.objects.filter(organization__id = org_id, role = 2)
        return render(request,'createTeams/status_to_admin.html',{'memberships':memberships,'warning':warning,'user':request.user},)
    else:
        return redirect('/')


'''
View used to change the status of members from admin(owner) to participant.
'''
def dismiss_admin(request,org_id):
    if request.user.is_authenticated:
        warning = ''
        admin = Membershiplevel.objects.filter(organization__id = org_id,role = 1).count()
        if request.method == 'POST':
            members = request.POST.getlist('checks')
            count = 0
            for member in members:
                count+=1
            if count==admin :
                warning = "Sorry, we can't change the status to participant!!"
            else:
                members = User.objects.filter(pk__in = members)
                Membershiplevel.change_role_participant(members,org_id)
                warning = "Role changed to participant successfully!!"

        memberships = Membershiplevel.objects.filter(organization__id = org_id, role = 1)
        return render(request,'createTeams/status_to_participant.html',{'memberships':memberships,'warning':warning,'user':request.user},)
    else:
        return redirect('/')


'''
View being called for leaving the team.
If the user leaving the team is admin of the team or any of its parent organizations,
then on leaving, some other person should be made as admin
if count of admins(owners) for the team equals 1(i.e. the user himself)
if count of admins(owners) for the team > 1, then user could easily leave the team
if user is participant and if he is the only person left in the team, then on leaving,
team and all its child organizations(channels) are deleted.
else the user could leave the team easily
'''
def leave_team(request,org_id):
    if request.method == 'POST':
        team = Organization.objects.get(pk=org_id)
        if request.POST.get('confirmation')=='clicked_yes':
            team = Organization.objects.get(pk=org_id)
            warning=''     
            flag = False
            par_id = Organization.objects.get(pk=org_id).parent_org_id
            org_name = Organization.objects.get(pk=org_id).name
            while par_id is not None:
                role = Membershiplevel.objects.get(user_id = request.user.id, organization__id = par_id).role
                if role == 1:
                    flag = True
                    break
                par_id = Organization.objects.get(pk=par_id).parent_org
            if flag == True:
                warning = "Sorry, You can't leave the team!!"
            else:
                # retrieving all the channels of team and storing their ids in child[]
                child = []
                retrieve_child_org(org_id,child)
                child.append(org_id)

                for org in child:
                    # checking whether the user is a part of any of the channels
                    if Membershiplevel.objects.filter(organization__id=org,user_id=request.user.id).exists():

                        role = Membershiplevel.objects.get(organization__id = org , user_id = request.user.id).role
                        curr_user = User.objects.get(pk = request.user.id)
                        total_members = Membershiplevel.objects.filter(organization__id = org).count()
                        if total_members>1:
                            # if the person is admin
                            if role == 1:
                                admin_count = Membershiplevel.objects.filter(organization__id = org,role = 1).count()
                                # if count of admin >1 then the person could easily leave the team
                                if admin_count > 1:
                                    Membershiplevel.leave_team(curr_user,org)
                                    warning = "Left the team successfully!!"
                                else:  
                                    # if count of admin equals 1, then before leaving,
                                    # some random person should be made as admin of the team
                                    members = Membershiplevel.objects.filter(organization__id = org)
                                    # accessing the random member of team to be made as admin. 
                                    user = Membershiplevel.access_new_admin(members,org,request.user.id)
                                    new_admin = User.objects.filter(pk=user)
                                    # changing the status of randomly selected person as admin
                                    Membershiplevel.change_role(new_admin,org)
                                    # current user(also the previous admin or owner) leaving the team
                                    Membershiplevel.leave_team(curr_user,org)
                                    warning = "Left the team successfully"
                            else:
                                # if the person is participant
                                Membershiplevel.leave_team(curr_user,org)

createTeams/templates/createTeams/add_members.html
{% extends 'createTeams/base.html' %}
{% load static %}
{% block title %}<title>Add new members</title>{% endblock title %}
{% block main-content %}
<div class="wrapper fadeInDown" style="padding-top:10%;">
    <div id="formContent" style="box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(80, 88, 94); ">
    <h1 style="color: white"> Add members </h1>
  <form method="post" >
    {% csrf_token %}
    
    <label for="team_members" style="color: white; font-size: 25px">Users:</label><br />
    <div id="team_members" multiple="true" name="checks" style="color:black; font-size: 18px"></div>
    <br />
    <input type="submit" class = "fadeIn" value="Add members to {{org.name}}" style="font-size: 15px">
    {% if warning%} {{warning}} {% endif %}<br />
  </form>
  </div>
  </div>
  <script>
    var ids = [];
    var names = [];
    var admin = [];
    var user_id="{{user.id}}";
    ("{% for membership in memberships %}");
    /*ids.push("{{membership.user.id}}");
    names.push("{{membership.user}}");
    admin.push("{{membership.role}}");*/
    ids.push("{{membership.id}}");
    names.push("{{membership.username}}");
    admin.push("{{membership.role}}");
    console.log(ids);
    console.log(names);
    console.log(admin);
    ("{% endfor %}");
  </script>
  <script src="{% static 'js/create_team.js' %}"></script>
{% endblock main-content %}

createTeams/templates/createTeams/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

    <head>
		<meta charset="utf-8">
		{% block title %}{% endblock title %}
		<meta name="description" content="#">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="{% static 'dist/css/lib/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
        <link href="{% static 'dist/css/swipe.min.css' %}" type="text/css" rel="stylesheet">
        <link rel="stylesheet" href="{% static '/css/base1.css' %}">
        <link rel="stylesheet" href="{% static '/css/settings.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <style>
            .material-icons{
                color: #242325;
                font-size: 30px !important;
            }
            .material-icons:hover{
                color:  #2196F3;
            }
            .navigation .container{
                padding-right: 10px;
                margin-right: 0px;
                margin: 0px;
            }
        </style>
		{% block mycss %}{% endblock mycss %}
    </head>
    <body>
        <main>
        <div class="layout">
            <div class="navigation" style="box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(115, 118, 121); position: fixed;">
                <div class="container" >
                    <div class="inside" >
                        <div class="nav nav-tab menu" >
                            <a href="{% url 'createTeams:new_team' %}" title = "create new team"><i class="fas fa-plus-square material-icons"></i></a>
                            <a href="{% url 'createTeams:display_teams' %}" data-target="#"  class="f-grow1" title="show teams"><i class="fas fa-users material-icons" ></i></a>
                            
                            <a href="{% url 'auth:pwdchange' %}" title="change password"><i class="fas fa-unlock material-icons"></i></a>
                            <a href="{% url 'auth:logout' %}" title="sign-out"><i class="material-icons">power_settings_new</i></a>
                        </div>
                    </div>
                </div>
            </div>
        {% block main-content %}{% endblock main-content %}
        </div>
        </main>
		<script src="{% static 'dist/js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script>window.jQuery || document.write('<script src="{% static "dist/js/vendor/jquery-slim.min.js" %}"><\/script>')</script>
		<script src="{% static 'dist/js/vendor/popper.min.js' %}"></script>
		<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    </body>
</html>

createTeams/templates/createTeams/team_page.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
		<meta charset="utf-8">
		<title>View Team</title>
		<meta name="description" content="#">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="{% static 'dist/css/lib/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'dist/css/swipe.min.css' %}" type="text/css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
        
        <style>
            .material-icons{
                color: #242325;
                font-size: 30px !important;
            }
            .material-icons:hover{
                color:  #2196F3;
            }
            .navigation .container{
                padding-right: 10px;
                margin-right: 0px;
                margin: 0px;
            }
            hr{
                background-color: black !important;
            }
            .text-group{
                color: black;
            }
            .icon-cg{
                color: #242325;
            }
        </style>
</head>
<body>
<main>
<div class="layout">
    <div class="navigation"style="background-color: rgb(248,248,248);box-shadow:  -3px -2px 1px 0 #f1ecec,-4px -2px 20px 0 rgb(115, 118, 121);" >
        <div class="container" >
            <div class="inside" >
                <div class="nav nav-tab menu" >
                    
                    
                    <a href="{% url 'createTeams:new_team' %}" title = "create new team"><i class="fas fa-plus-square material-icons"></i></a>
                    <a href="{% url 'createTeams:display_teams' %}" data-target="#"  class="f-grow1" title="show teams"><i class="fas fa-users material-icons" ></i></a>
                    
                    <a href="{% url 'auth:pwdchange' %}" title="change password"><i class="fas fa-unlock material-icons"></i></a>
                    <a href="{% url 'auth:logout' %}" title="sign-out"><i class="material-icons">power_settings_new</i></a>
                </div>
            </div>
        </div>
    </div>
    
<div class="sidebar" id="sidebar" style="background-color: rgb(226, 224, 224)">
    <div class="container">
        <div class="col-md-12">
            <div class="tab-content">
                <div id="discussions" class="tab-pane fade active show">
                    <div class="search">
                        <a href="{% url 'createTeams:display_teams' %}"><h2 style="color: #242325;margin-left: 0%;margin-top: 2%;font-size:20px;font-weight:bold"><i class="fas fa-angle-double-left"></i> All Teams</h2></a>
                        {% ifequal user_role 1 %}
                        <a href="{% url 'createTeams:add_members' org.id %}"><button class="btn create" data-toggle="modal" data-target="#startnewchat" title = "Add members"><i class="fas fa-user-plus"></i></button></a>
                        {% else %}
                        <button class="btn create" data-toggle="modal" data-target="#startnewchat" title="Access granted to owners only"><i class="fas fa-user-plus"></i></button>
                        {% endifequal %}
                    </div>					
                    <div class="discussions">
                        <i class="fas fa-users fa-6x icon-cg"></i><h1>{{org.name}}{% if org.parent_org is not null %}-<a href="{% url 'createTeams:view_team' org.parent_org.id %}">{{org.parent_org.name}}{% endif %}</a></h1>
                        <div class="list-group" id="chats" role="tablist">
                            {% for channel in channels %}
                            <a href="{% url 'createTeams:view_team' channel.id %}" class="filterDiscussions all unread single active" id="list-chat-list" >
                                
                                <div class="data">
                                    <h5>{{channel.name}}</h5>
                                </div>
                            </a>
                            {% endfor %}										
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>  
</div>  
<div class="main" style="background: rgb(223, 223, 223);">
    <div class="tab-content" id="nav-tabContent" style="width: 100%; background: rgb(223, 223, 223)">
        <div class="babble tab-pane fade active show" id="list-chat" role="tabpanel" aria-labelledby="list-chat-list">
            <div class="chat" id="chat1" style="background: rgb(223, 223, 223)">
                <div class="top" style="background: rgb(223, 223, 223)">
                    <div class="container" >
                        <div class="col">
                            <div class="inside">
                                <div class="data">
                                    <h4 style="color:black;">{{org.name}}</h4>
                                    <span>{{org.description}}</span>
                                </div>
                                <a href="{% url 'createTeams:send_invite' org.id %}"><button id = "video_btn" class="btn connect d-md-block d-none" name="1" title="video call"><i class="material-icons md-36">videocam</i></button></a>
                                <div class="dropdown">
                                    <button class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="material-icons md-30">more_vert</i></button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a href="{% url 'createTeams:send_invite' org.id %}"><button class="dropdown-item connect" name="1"><i class="material-icons">videocam</i>Video Call</button></a>
                                        <a href="{% url 'createTeams:leave_team' org.id %}"><button class="dropdown-item"><i class="material-icons">block</i>Leave Team</button></a>
                                        <hr>
                                        {% ifequal user_role 1 %}
                                        <a href="{% url 'createTeams:add_members' org.id %}"><button class="dropdown-item connect" name="1"><i class="fas fa-user-plus material-icons"></i>Add member</button></a>
                                        <a href="{% url 'createTeams:create_team' org.id %}"><button class="dropdown-item"><i class="fas fa-plus-square material-icons"></i>Add Channel</button></a>
                                        <a href="{% url 'createTeams:edit_team' org.id %}"><button class="dropdown-item"><i class="fas fa-edit material-icons"></i> Edit Team</button></a>
                                        <a href="{% url 'createTeams:change_role' org.id %}"><button class="dropdown-item"><i class="fas fa-user-shield material-icons"></i>Make members as admins</button></a>
                                        <a href="{% url 'createTeams:dismiss_admin' org.id %}"><button class="dropdown-item"><i class="fas fa-user material-icons"></i> Remove Owners</button></a>
                                        <a href="{% url 'createTeams:delete_team' org.id %}"><button class="dropdown-item"><i class="fas fa-trash material-icons"></i> Delete Team</button></a>                                        
                                        {% endifequal %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content" id="content">
                    <div class="container">
                        <div id="message_chat_container" class="col-md-12">
                            
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="col-md-12">
                        <div class="bottom">
                            <div class="position-relative w-100">
                                <div contenteditable="true" class="form-control" name="chat-message-input" id = "chat-message-input" placeholder="Start typing for reply..." rows="1"></div>
                                <button type="submit" id = "chat-message-submit" class="btn send" title="send"><i class="material-icons">send</i></button>
                            </div>   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>        
</div>
</main>
<script src = "{% static 'js/reconnecting-websocket.js' %}"></script>
    <script>
        var user_name = '{{user.username}}'
        const room_id = '{{org.id}}'

        const chatSocket = new ReconnectingWebSocket(
            'ws://'
            + window.location.host
            + '/ws/createTeams/view_team/'
            + room_id
            + '/'
        );
        chatSocket.onopen = function(e){
            fetchMessages();
        }

        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            if(data['command'] === 'messages'){
                for(let i=0;i<data['messages'].length;i++){
                    createMessage(data['messages'][i]);
                }
            }
            else if (data['command'] === 'new_message'){
                createMessage(data['message']);
            }       
        };

        function createMessage(data)
        {
            var author = data['user']
            var spantag = document.createElement('span');
            var divtext = document.createElement('div');
            var divtextgroup = document.createElement('div');
            var divtextmain = document.createElement('div');
            var divmessage = document.createElement('div');
            var ptag = document.createElement('p');
            var atag = document.createElement('a');
            ptag.textContent = data.content;
            divtextmain.className = "text-main";
            if(author == user_name){
                divtext.className = "text me";
                divtextgroup.className = "text-group me";
                divmessage.className = "message me";
            }
            else{
                divtext.className = "text";
                divtextgroup.className = "text-group";
                divmessage.className = "message";
                spantag.textContent = author;
                divtext.appendChild(spantag);
            }
            
            divtext.appendChild(ptag);
            divtextgroup.appendChild(divtext);
            divtextmain.appendChild(divtextgroup);
            divmessage.appendChild(divtextmain);
            document.querySelector('#message_chat_container').appendChild(divmessage);
        }

        function fetchMessages(){
            chatSocket.send(JSON.stringify({'command':'fetch_messages','room_id': room_id}));
        }

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.textContent;
            console.log("message:",message)
            chatSocket.send(JSON.stringify({
                'message': message,
                'command':'new_message',
                'from': user_name,
                'room_id': room_id
            }));
            messageInputDom.textContent = '';
        };
    </script>

    <!--  <script type="text/javascript">
    $('#video_btn').click(function(){
    var orgid;
    orgid = $(this).attr("data-orgid");

    $.ajax(
    {
        type:"GET",
        url: "{% url 'createTeams:send_invite' org.id %}",
        data:{
                 'org_id': orgid,
        },
        dataType: 'json',
        success: function( data ) 
        {
            $( '#chat-message-input' ).val(data.redirect);
            $('#chat-message-submit').click();
            alert(data)
            window.location.href = data.redirect;
        }
    })
});
</script> -->
<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="{% static 'dist/js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script>window.jQuery || document.write('<script src="{% static "dist/js/vendor/jquery-slim.min.js" %}"><\/script>')</script>
		<script src="{% static 'dist/js/vendor/popper.min.js' %}"></script>
        <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
        <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
</body>
</html>